# Creates a Microsoft 365 Apps package and optionally imports into a target Intune tenant
# Uses secrets on the repo - TENANT_ID, CLIENT_ID, and CLIENT_SECRET
# to import the package into a target tenant
name: New package

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Configuration file
        type: choice
        options:
          - O365ProPlusVisioProRetailProjectProRetail.xml
          - O365ProPlus.xml
          - O365BusinessRetail.xml
          - O365ProPlusVisioProRetailProjectProRetail-VDI.xml          
          - O365ProPlus-VDI.xml
          - O365BusinessRetail-VDI.xml
      channel:
        description: Update channel
        type: choice
        options:
          - MonthlyEnterprise
          - Current
          - SemiAnnual
          - SemiAnnualPreview
          - CurrentPreview
          - BetaChannel
      companyname:
        description: Company name
        required: false
        default: stealthpuppy
      import:
        description: "Import? (if not selected, download package from pipeline artifacts)"
        default: true
        type: boolean

jobs:
  new-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test configuration file path
        id: test-config
        shell: powershell
        working-directory: "${{ github.workspace }}"
        run: |
          if (-not (Test-Path -Path "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}")) { throw "Could not find configration file: ${{ github.event.inputs.configuration }}" }

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: "Evergreen::, MSAL.PS::, IntuneWin32App::"
          updatable: true
          shell: powershell

      - name: Create and Import package
        id: import-package
        if:  ${{ github.event.inputs.import == 'true' }}
        shell: powershell
        working-directory: "${{ github.workspace }}"
        run: |
          $params = @{
              Path              = "${{ github.workspace }}"
              ConfigurationFile  = "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}"
              Channel           = "${{ github.event.inputs.channel }}"
              CompanyName       = "${{ github.event.inputs.companyname }}"
              TenantId          = "${{ secrets.TENANT_ID }}"
              ClientId          = "${{ secrets.CLIENT_ID }}"
              ClientSecret      = "${{ secrets.CLIENT_SECRET }}"
              Import            = $true
              Verbose           = $true
          }
          & "${{ github.workspace }}\New-Microsoft365AppsPackage.ps1" @params

      - name: Create package artifact only
        id: create-artifact
        if:  ${{ github.event.inputs.import == 'false' }}
        shell: powershell
        working-directory: "${{ github.workspace }}"
        run: |
          $params = @{
              Path              = "${{ github.workspace }}"
              ConfigurationFile  = "${{ github.workspace }}\configs\${{ github.event.inputs.configuration }}"
              Channel           = "${{ github.event.inputs.channel }}"
              CompanyName       = "${{ github.event.inputs.companyname }}"
              TenantId          = "${{ secrets.TENANT_ID }}"
              ClientId          = "${{ secrets.CLIENT_ID }}"
              ClientSecret      = "${{ secrets.CLIENT_SECRET }}"
              Import            = $false
              Verbose           = $true
          }
          & "${{ github.workspace }}\New-Microsoft365AppsPackage.ps1" @params

      - name: Set release
        id: release
        shell: powershell
        run: |
          $ConfigurationFile = Get-ChildItem -Path ${{ github.workspace }}\package\output\*.xml | Select-Object -First 1
          $FileName = [System.IO.Path]::GetFileNameWithoutExtension($ConfigurationFile)
          [System.Xml.XmlDocument]$Xml = Get-Content -Path $ConfigurationFile
          $Channel = $Xml.Configuration.Add.Channel
          $Date = Get-Date -Format yyyyMMdd
          echo "release=$FileName.$Channel.$Date.${{ github.run_number }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding Utf8 -Append

      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "m365-${{ steps.release.outputs.release }}"
          path: |
            ${{ github.workspace }}/package/output/*
